### 장바구니 등록
DELETE http://localhost:8080/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiI1MiIsImVtYWlsIjoibXl0ZXN0MUBuYXZlci5jb20iLCJpc3MiOiJmY19taW5pIiwiaWF0IjoxNzAxMjQyMzc2LCJleHAiOjE3MDEyNzgzNzZ9.k-iDVqJs7BWGkwr7A1dT_lVSOXn1T5lXqqvfzJqoofiptkOvZ8LpC---CiILeqKkIFgCVOOIIxfkmiJqf48Dlw

{
  "delete_id": [1]
}